"""id autogenerate

Revision ID: 69170cf52910
Revises: cb39e2519c71
Create Date: 2026-02-05 14:57:03.258633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69170cf52910"
down_revision: Union[str, Sequence[str], None] = "cb39e2519c71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order_items", "id", existing_type=sa.UUID(), server_default=sa.text("gen_random_uuid()"), existing_nullable=False)
    op.alter_column("orders", "id", existing_type=sa.UUID(), server_default=sa.text("gen_random_uuid()"), existing_nullable=False)
    op.alter_column("outbox_events", "id", existing_type=sa.UUID(), server_default=sa.text("gen_random_uuid()"), existing_nullable=False)
    op.alter_column("refresh_tokens", "id", existing_type=sa.UUID(), server_default=sa.text("gen_random_uuid()"), existing_nullable=False)
    op.alter_column("users", "id", existing_type=sa.UUID(), server_default=sa.text("gen_random_uuid()"), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.alter_column("refresh_tokens", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.alter_column("outbox_events", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.alter_column("orders", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    op.alter_column("order_items", "id", existing_type=sa.UUID(), server_default=None, existing_nullable=False)
    # ### end Alembic commands ###
