"""fix some db issue

Revision ID: 80a40c80b137
Revises: 8bd01c7b5105
Create Date: 2026-02-04 20:00:01.751536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80a40c80b137"
down_revision: Union[str, Sequence[str], None] = "8bd01c7b5105"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("idempotency_key", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("orders_idemopotency_key_key"), "orders", type_="unique")
    op.create_unique_constraint("uq_order_idempotency_key_user_id", "orders", ["idempotency_key", "user_id"])
    op.drop_column("orders", "idemopotency_key")
    op.drop_index(op.f("ix_outbox_events_created_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_published_at"), table_name="outbox_events")
    op.create_index("ix_outbox_events_published_at_created_at", "outbox_events", ["published_at", "created_at"], unique=False)
    op.add_column("refresh_tokens", sa.Column("token_hash", sa.String(), nullable=False))
    op.drop_constraint(op.f("refresh_tokens_token_key"), "refresh_tokens", type_="unique")
    op.create_unique_constraint(None, "refresh_tokens", ["token_hash"])
    op.drop_column("refresh_tokens", "token")
    op.drop_index(op.f("ix_user_email"), table_name="users")
    op.create_index("ix_user_email", "users", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_email", table_name="users")
    op.create_index(op.f("ix_user_email"), "users", ["email"], unique=True)
    op.add_column("refresh_tokens", sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "refresh_tokens", type_="unique")
    op.create_unique_constraint(op.f("refresh_tokens_token_key"), "refresh_tokens", ["token"], postgresql_nulls_not_distinct=False)
    op.drop_column("refresh_tokens", "token_hash")
    op.drop_index("ix_outbox_events_published_at_created_at", table_name="outbox_events")
    op.create_index(op.f("ix_outbox_events_published_at"), "outbox_events", ["published_at"], unique=False)
    op.create_index(op.f("ix_outbox_events_created_at"), "outbox_events", ["created_at"], unique=False)
    op.add_column("orders", sa.Column("idemopotency_key", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint("uq_order_idempotency_key_user_id", "orders", type_="unique")
    op.create_unique_constraint(op.f("orders_idemopotency_key_key"), "orders", ["idemopotency_key"], postgresql_nulls_not_distinct=False)
    op.drop_column("orders", "idempotency_key")
    # ### end Alembic commands ###
