"""id autogenerate

Revision ID: a1faf38b0c1f
Revises: 80a40c80b137
Create Date: 2026-02-05 14:47:47.425745

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a1faf38b0c1f"
down_revision: Union[str, Sequence[str], None] = "80a40c80b137"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
