"""Add orders table

Revision ID: a3e4580346e8
Revises: ca11080dfc5b
Create Date: 2026-02-01 17:24:26.199259

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a3e4580346e8"
down_revision: Union[str, Sequence[str], None] = "ca11080dfc5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
