"""Index user mail

Revision ID: ca11080dfc5b
Revises: d68513a8194d
Create Date: 2026-02-01 17:03:12.798429

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ca11080dfc5b"
down_revision: Union[str, Sequence[str], None] = "d68513a8194d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_email", "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_email", table_name="users")
    # ### end Alembic commands ###
