"""id autogenerate

Revision ID: cb39e2519c71
Revises: a1faf38b0c1f
Create Date: 2026-02-05 14:53:08.921168

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cb39e2519c71"
down_revision: Union[str, Sequence[str], None] = "a1faf38b0c1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
